server:
  hostname: localhost
  port: ${PORT:8090}
spring:
  application:
    name: trueshop
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    name: 'dataTrueShop'
#    jdbc:mysql://localhost:3306/TrueShop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATABASE_PATH}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.ws: DEBUG








