server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    name: 'dataTrueShop'
    url: jdbc:mysql://localhost:3306/TrueShop?serverTimezone=UTC
    username: root
    password: Nbirf
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.ws: DEBUG








