server:
  port: 8090
spring:
  mvc:
    static-path-pattern: /statico/**
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    name: 'dataTrueShop'
    url: jdbc:mysql://localhost:3306/TrueShop?serverTimezone=UTC
    username: root
    password: Nbirf
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings







