//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.15 at 11:59:37 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kuznetsovka.com/trueshop/ws/greeting", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kuznetsovka.trueshop.ws.greeting;
