alter table bucket_products drop foreign key FKd3uv4vwg7eybaqclvc2sn4i5k;
alter table bucket_products drop foreign key FKt11v7b7hocd7iprbkn3v0cui5;
alter table buckets drop foreign key FKnl0ltaj67xhydcrfbq8401nvj;
alter table comparison_products drop foreign key FKc2jjwal56i23c1tt2hnfpciao;
alter table comparison_products drop foreign key FKoicehcydibpvm89tenfskiwj1;
alter table comparisons drop foreign key FKj9f9faabny48m6rmp1b2uxskc;
alter table favourite_products drop foreign key FKb4hw44beqrhil8f12qx5026v2;
alter table favourite_products drop foreign key FKf28muekvrgh648xihbkfv4wdo;
alter table favourites drop foreign key FK6ffqdnwmm3ks4fenx2ml1uap8;
alter table orders drop foreign key FK32ql8ubntj5uh44ph9659tiih;
alter table orders_details drop foreign key FK5o977kj2vptwo70fu7w7so9fe;
alter table orders_details drop foreign key FKs0r9x49croribb4j6tah648gt;
alter table place_in_stock_products drop foreign key FKlyasoqgulnm0gbnd1tvs4gp6b;
alter table place_in_stock_products drop foreign key FKg47bu6ug0i0t4f7etitdl9umr;
alter table products_categories drop foreign key FKqt6m2o5dly3luqcm00f5t4h2p;
alter table products_categories drop foreign key FKtj1vdea8qwerbjqie4xldl1el;
alter table products_place_in_stock drop foreign key FKh8sler2j6pmorrbp8a6lgli4k;
alter table products_place_in_stock drop foreign key FK3hlfn1pk19kxuxii9w4ai20a7;
alter table products_suppliers drop foreign key FKsgpbuup22gs5mhvw2lgicxws4;
alter table products_suppliers drop foreign key FKbmpkpgd8vx6o1vq8exi6in76s;
alter table suppliers_products drop foreign key FKlbph1a19ss69wvvdm0gq18rl6;
alter table suppliers_products drop foreign key FKdpy1wg96qkljeo1xh1cox05r9;
alter table users drop foreign key FK8l2qc4c6gihjdyoch727guci;
alter table users drop foreign key FKovi6xowjrgghpckhqv758ohp5;
alter table users drop foreign key FKnkifqqqp5hgh8ort55ed9pyyr;
drop table if exists bucket_products;
drop table if exists bucket_seq;
drop table if exists buckets;
drop table if exists categories;
drop table if exists category_seq;
drop table if exists comparison_products;
drop table if exists comparison_seq;
drop table if exists comparisons;
drop table if exists favourite_products;
drop table if exists favourite_seq;
drop table if exists favourites;
drop table if exists order_details_seq;
drop table if exists order_seq;
drop table if exists orders;
drop table if exists orders_details;
drop table if exists place_in_stock;
drop table if exists place_in_stock_products;
drop table if exists place_seq;
drop table if exists product_seq;
drop table if exists products;
drop table if exists products_categories;
drop table if exists products_place_in_stock;
drop table if exists products_suppliers;
drop table if exists supplier_seq;
drop table if exists suppliers;
drop table if exists suppliers_products;
drop table if exists user_seq;
drop table if exists users;
create table bucket_products (bucket_id bigint not null, product_id bigint not null) engine=InnoDB;
create table bucket_seq (next_val bigint) engine=InnoDB;
insert into bucket_seq values ( 1 );
create table buckets (id bigint not null, user_id bigint, primary key (id)) engine=InnoDB;
create table categories (id bigint not null, title varchar(255), primary key (id)) engine=InnoDB;
create table category_seq (next_val bigint) engine=InnoDB;
insert into category_seq values ( 1 );
create table comparison_products (comparison_id bigint not null, product_id bigint not null) engine=InnoDB;
create table comparison_seq (next_val bigint) engine=InnoDB;
insert into comparison_seq values ( 1 );
create table comparisons (id bigint not null, user_id bigint, primary key (id)) engine=InnoDB;
create table favourite_products (favourite_id bigint not null, product_id bigint not null) engine=InnoDB;
create table favourite_seq (next_val bigint) engine=InnoDB;
insert into favourite_seq values ( 1 );
create table favourites (id bigint not null, user_id bigint, primary key (id)) engine=InnoDB;
create table order_details_seq (next_val bigint) engine=InnoDB;
insert into order_details_seq values ( 1 );
create table order_seq (next_val bigint) engine=InnoDB;
insert into order_seq values ( 1 );
create table orders (id bigint not null, address varchar(255), changed datetime(6), created datetime(6), status varchar(255), sum decimal(19,2), user_id bigint, primary key (id)) engine=InnoDB;
create table orders_details (id bigint not null, amount decimal(19,2), price decimal(19,2), order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table place_in_stock (id bigint not null, place_fld integer not null, row_fld integer not null, shelf_fld integer not null, span_fld integer not null, primary key (id)) engine=InnoDB;
create table place_in_stock_products (place_in_stock_id bigint not null, product_id bigint not null) engine=InnoDB;
create table place_seq (next_val bigint) engine=InnoDB;
insert into place_seq values ( 1 );
create table product_seq (next_val bigint) engine=InnoDB;
insert into product_seq values ( 1 );
create table products (id bigint not null, price double precision, title varchar(255), primary key (id)) engine=InnoDB;
create table products_categories (product_id bigint not null, category_id bigint not null) engine=InnoDB;
create table products_place_in_stock (product_id bigint not null, place_in_stock_id bigint not null) engine=InnoDB;
create table products_suppliers (product_id bigint not null, supplier_id bigint not null) engine=InnoDB;
create table supplier_seq (next_val bigint) engine=InnoDB;
insert into supplier_seq values ( 1 );
create table suppliers (id bigint not null, title varchar(255), primary key (id)) engine=InnoDB;
create table suppliers_products (supplier_id bigint not null, product_id bigint not null) engine=InnoDB;
create table user_seq (next_val bigint) engine=InnoDB;
insert into user_seq values ( 1 );
create table users (id bigint not null, archive bit not null, email varchar(255), name varchar(255), password varchar(255), role varchar(255), bucket_id bigint, comparison_id bigint, favourite_id bigint, primary key (id)) engine=InnoDB;
alter table bucket_products add constraint FKd3uv4vwg7eybaqclvc2sn4i5k foreign key (product_id) references products (id);
alter table bucket_products add constraint FKt11v7b7hocd7iprbkn3v0cui5 foreign key (bucket_id) references buckets (id);
alter table buckets add constraint FKnl0ltaj67xhydcrfbq8401nvj foreign key (user_id) references users (id);
alter table comparison_products add constraint FKc2jjwal56i23c1tt2hnfpciao foreign key (product_id) references products (id);
alter table comparison_products add constraint FKoicehcydibpvm89tenfskiwj1 foreign key (comparison_id) references comparisons (id);
alter table comparisons add constraint FKj9f9faabny48m6rmp1b2uxskc foreign key (user_id) references users (id);
alter table favourite_products add constraint FKb4hw44beqrhil8f12qx5026v2 foreign key (product_id) references products (id);
alter table favourite_products add constraint FKf28muekvrgh648xihbkfv4wdo foreign key (favourite_id) references favourites (id);
alter table favourites add constraint FK6ffqdnwmm3ks4fenx2ml1uap8 foreign key (user_id) references users (id);
alter table orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table orders_details add constraint FK5o977kj2vptwo70fu7w7so9fe foreign key (order_id) references orders (id);
alter table orders_details add constraint FKs0r9x49croribb4j6tah648gt foreign key (product_id) references products (id);
alter table place_in_stock_products add constraint FKlyasoqgulnm0gbnd1tvs4gp6b foreign key (product_id) references products (id);
alter table place_in_stock_products add constraint FKg47bu6ug0i0t4f7etitdl9umr foreign key (place_in_stock_id) references place_in_stock (id);
alter table products_categories add constraint FKqt6m2o5dly3luqcm00f5t4h2p foreign key (category_id) references categories (id);
alter table products_categories add constraint FKtj1vdea8qwerbjqie4xldl1el foreign key (product_id) references products (id);
alter table products_place_in_stock add constraint FKh8sler2j6pmorrbp8a6lgli4k foreign key (place_in_stock_id) references place_in_stock (id);
alter table products_place_in_stock add constraint FK3hlfn1pk19kxuxii9w4ai20a7 foreign key (product_id) references products (id);
alter table products_suppliers add constraint FKsgpbuup22gs5mhvw2lgicxws4 foreign key (supplier_id) references suppliers (id);
alter table products_suppliers add constraint FKbmpkpgd8vx6o1vq8exi6in76s foreign key (product_id) references products (id);
alter table suppliers_products add constraint FKlbph1a19ss69wvvdm0gq18rl6 foreign key (product_id) references products (id);
alter table suppliers_products add constraint FKdpy1wg96qkljeo1xh1cox05r9 foreign key (supplier_id) references suppliers (id);
alter table users add constraint FK8l2qc4c6gihjdyoch727guci foreign key (bucket_id) references buckets (id);
alter table users add constraint FKovi6xowjrgghpckhqv758ohp5 foreign key (comparison_id) references comparisons (id);
alter table users add constraint FKnkifqqqp5hgh8ort55ed9pyyr foreign key (favourite_id) references favourites (id);